### ISSUE TITLE
mysql: Disable debug logs in non-verbose mode

### ISSUE THREAD

**Issue by justinbastress** [zmap/zgrab2#114]
Logs are getting spammed with e.g.

`:time="2018-05-10T17:14:12-04:00" level=debug msg="Failed to detect error from Server returned error after connecting: error_code = 0x46a; error_message = Host '...' is not allowed to connect to this MySQL server at goroutine 277 [running]:\nruntime/debug.Stack(0xae47c0, 0xc421efa5a0, 0xc420068040)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/zmap/zgrab2.TryGetScanStatus(0xae47c0, 0xc421efa5a0, 0xc421efa5a0, 0xae47c0)\n\t/var/search/tmp/go/src/github.com/zmap/zgrab2/status.go:92 +0x2b9\ngithub.com/zmap/zgrab2/modules/mysql.(*Scanner).Scan.func1(0xc421987bc0, 0xc421987ba0, 0xc42016ba90, 0xc421987bb0, 0xc421987b48)\n\t/var/search/tmp/go/src/github.com/zmap/zgrab2/modules/mysql/scanner.go:206 +0x189\npanic(0x988880, 0xc421efa5a0)\n\t/usr/local/go/src/runtime/panic.go:502 +0x229\ngithub.com/zmap/zgrab2/modules/mysql.(*Scanner).Scan(0xc42015c4c0, 0xc4214e3260, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/var/search/tmp/go/src/github.com/zmap/zgrab2/modules/mysql/scanner.go:221 +0x348\ngithub.com/zmap/zgrab2.RunScanner(0xaec040, 0xc42015c4c0, 0xc4204108b0, 0xc4214e3260, 0x10, 0x10, 0x0, 0x0, 0xa56c59, 0x5, ...)\n\t/var/search/tmp/go/src/github.com/zmap/zgrab2/scanner.go:32 +0xd1\ngithub.com/zmap/zgrab2.grabTarget(0xc4214e3260, 0x10, 0x10, 0x0, 0x0, 0xc4204108b0, 0x0, 0x0, 0x0)\n\t/var/search/tmp/go/src/github.com/zmap/zgrab2/processing.go:92 +0x219\ngithub.com/zmap/zgrab2.Process.func2(0xc420169680, 0xc4204108b0, 0xc42050c000, 0xc4204c0050, 0xed)\n\t/var/search/tmp/go/src/github.com/zmap/zgrab2/processing.go:159 +0x126\ncreated by github.com/zmap/zgrab2.Process\n\t/var/search/tmp/go/src/github.com/zmap/zgrab2/processing.go:152 +0x191\n"`

**Comment by justinbastress** [comment]
Fixed.
