### ISSUE TITLE
http scan ERRO[0527]

### ISSUE THREAD

**Issue by MushR00m** [zmap/zgrab2#319]
#### error logs

```
ERRO[0527] Panic on scanner http.80 when scanning target 10.x.x.x(ipaddress): runtime.boundsError{x:128, y:50, signed:true, code:0x1} 
panic: runtime error: slice bounds out of range [:128] with length 50 [recovered]
        panic: runtime error: slice bounds out of range [:128] with length 50

goroutine 509 [running]:
github.com/zmap/zgrab2.grabTarget.func1(0xc00e963f00, 0xc01204a180, 0xc000279d36, 0x7)
        /xx/zmapro/zgrab2/processing.go:165 +0x1f1
panic(0xbfa200, 0xc009282d20)
        /usr/lib/golang/src/runtime/panic.go:975 +0x47a
github.com/zmap/zgrab2/modules/http.(*scan).Grab(0xc004721400, 0x0)
        /xxx/zgrab2/modules/http/scanner.go:553 +0x10c5
github.com/zmap/zgrab2/modules/http.(*Scanner).Scan(0xc00024bf80, 0xc0096ad6c0, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /xxx/zgrab2/modules/http/scanner.go:592 +0xee
github.com/zmap/zgrab2.RunScanner(0xd70b00, 0xc00024bf80, 0xc000458080, 0xc0096ad6c0, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, ...)
        /xxx/zgrab2/scanner.go:32 +0xda
github.com/zmap/zgrab2.grabTarget(0xc0096ad6c0, 0x10, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000458080, 0x0, ...)
        /xxx/zgrab2/processing.go:168 +0x3dd
github.com/zmap/zgrab2.Process.func2(0xc000077680, 0xc000458080, 0xc0000776e0, 0xc0003f0fb0, 0x1f1)
        /xxx/zgrab2/processing.go:215 +0x145
created by github.com/zmap/zgrab2.Process
        /rxxx/zgrab2/processing.go:208 +0x167

```

**Comment by mzpqnxow** [comment]
Can you provide:

1. The command used to invoke `zgrab2`
2. Any other relevant inputs? Examples being a targets file (with triggers/tags if you use them)

I'm happy to take a quick look

Also, can you confirm when your local copy was built? Is it from a recent master? Since it's been 2+ months, is this still reproducible?

**Comment by MushR00m** [comment]
@vl4deee11 @mzpqnxow thanks!
